before_script:
  - apt-get update -qq && apt-get install -y -qq libssl-dev scons yasm libgmp-dev gcovr
  - wget -q http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz; tar xf boost_1_60_0.tar.gz ; mv boost_1_60_0/boost src/.
  - ./install_relic.sh
 
stages:

  - build
  - test
  
crypto:
  stage: build
  script:
  - scons static_relic=1
  
check:
  stage: test
  script:
  - scons check static_relic=1 no_aesni=1
  - scons -Q -c check
  - scons check debug=1 gcov=1 static_relic=1 
  - gcovr  -r . -f '(.*)src(.*)' -e '(.*)boost(.*)'
