branches:
   except:
     - doc
     - benchmarks

language: cpp

os: linux
dist: trusty
sudo: required


addons:
   apt:
     sources: &basic_sources
       - ubuntu-toolchain-r-test
       - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
         key_url: 'http://llvm.org/apt/llvm-snapshot.gpg.key'
     packages: &basic_deps
       - libssl-dev
       - libgmp-dev
       - lcov


env: MATRIX_EVAL="" 

matrix:
   include:
      - env: 
          - STATIC_ANALYSIS=false
          - MATRIX_EVAL="export CC="gcc-4.9" CXX="g++-4.9""
        addons:
            apt:
              sources: *basic_sources
              packages:
                 - *basic_deps
                 - g++-4.9 
      - env: 
          - STATIC_ANALYSIS=true
          - CLANG_TIDY=clang-tidy-5.0
        addons:
           apt:
              sources: *basic_sources
              packages:
                 - *basic_deps
                 - cppcheck
                 - clang-tidy-5.0

before_install:
  - eval "${MATRIX_EVAL}"  
  
install:  
  - if [ ! "${STATIC_ANALYSIS}" == "true" ]; then sudo apt-get install g++-4.9; fi # upload the report to coveralls
  - cd install_dependencies
  - ./install_libsodium.sh
  - ./install_relic_ubuntu_14_easy.sh
  - cd ..
  - gem install coveralls-lcov
  - sudo ldconfig
 
script:
  - if [ ! "${STATIC_ANALYSIS}" == "true" ]; then
      scons check debug=1 coverage=1 static_relic=1 sanitize_address=1 sanitize_undefined=1;
    fi
  - if [ "${STATIC_ANALYSIS}" == "true" ]; then
      ./scripts/cppcheck.sh;
      ./scripts/tidy.sh;
    fi
  

after_success:
  - ./coverage/gen_coverage.sh # get the code coverage
  - if [ ! "${STATIC_ANALYSIS}" == "true" ]; then ./coverage/upload_report.sh; fi # upload the report to coveralls
  
