branches:
   except:
     - doc
     - benchmarks

language: cpp

os: linux
dist: trusty
sudo: required
addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       # - g++-4.9
       - libssl-dev
       - libgmp-dev
       - lcov
       - cppcheck


env:
- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"
  # - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  # - cd install_dependencies
  # - ./install_libsodium.sh
  # - ./install_relic_ubuntu_14_easy.sh
  # - cd ..
  # - gem install coveralls-lcov
  # - sudo ldconfig
 
script:
  # - scons check debug=1 coverage=1 static_relic=1 sanitize_address=1 sanitize_undefined=1
  - ./scripts/cppcheck.sh

after_success:
  # - ./coverage/gen_coverage.sh # get the code coverage
  # - ./coverage/upload_report.sh # upload the report to coveralls