branches:
   except:
     - doc
     - benchmarks

language: cpp

os: linux
dist: trusty
sudo: required
addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       # - g++-4.9
       - libssl-dev
       - libgmp-dev
       - lcov
       - cppcheck


env:
- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9" STATIC_ANALYSIS=true

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  
  # - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  
install:  
  - if [ ! "${STATIC_ANALYSIS}" == "true" ]; then
      sudo apt-get install clang-tidy-5.0 -y;
    fi
  # - cd install_dependencies
  # - ./install_libsodium.sh
  # - ./install_relic_ubuntu_14_easy.sh
  # - cd ..
  # - gem install coveralls-lcov
  # - sudo ldconfig
 
script:
  - if [ ! "${STATIC_ANALYSIS}" == "true" ]; then
      scons check debug=1 coverage=1 static_relic=1 sanitize_address=1 sanitize_undefined=1;
    fi
  - if [ "${STATIC_ANALYSIS}" == "true" ]; then
      ./scripts/cppcheck.sh;
      ./scripts/tidy.sh;
    fi
  

after_success:
  - ./coverage/gen_coverage.sh # get the code coverage
  # - ./coverage/upload_report.sh # upload the report to coveralls